image: clever/drone-node:6.2.2
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  npm:
    token: $$npm_token
    when:
      branch: master
script:
- npm install
- npm test
