image: node0.10
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  npm:
    email: $$npm_drone_email
    password: $$npm_drone_password
    username: $$npm_drone_username
    when:
      branch: master
script:
- npm install
- npm test
- nvm install 0.10.29
- nvm use 0.10.29
